# Default values for chart.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

replicaCount: 1

image:
  repository: rg.fr-par.scw.cloud/thetribe/hr-for-impact-cms
  pullPolicy: Always
  # Overrides the image tag whose default is the chart appVersion.
  tag: "0.0.3"

imagePullSecrets: 
  - name: registry-secret

nameOverride: ""
fullnameOverride: ""

serviceAccount:
  create: false
  annotations: {}
  name: ""

podAnnotations: {}
podSecurityContext: {}
securityContext: {}

service:
  type: ClusterIP
  port: 1337

autoscaling:
  enabled: false
  minReplicas: 1
  maxReplicas: 5
  targetCPUUtilizationPercentage: 80
  # targetMemoryUtilizationPercentage: 80

nodeSelector: {}

tolerations: []

affinity: {}

namespace: 
  name: hr-for-impact
  enabled: true

env: []