# Default values for chart.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

replicaCount: 1

image:
  repository:
  pullPolicy: IfNotPresent
  # Overrides the image tag whose default is the chart appVersion.
  tag: "0.0.0"

imagePullSecrets:
  - name: registry-secret

nameOverride: ""
fullnameOverride: ""

serviceAccount:
  create: false
  annotations: {}
  name: ""

podAnnotations: {}
podSecurityContext: {}
securityContext: {}

service:
  type: ClusterIP
  port: 1337

autoscaling:
  enabled: false
  minReplicas: 1
  maxReplicas: 5
  targetCPUUtilizationPercentage: 80
  # targetMemoryUtilizationPercentage: 80

nodeSelector: {}

tolerations: []

affinity: {}

namespace:
  name:
env:
  - name: from
    value: helm

database:
  host:
  port: "1234"
  password:
  username:
  db_name:

security:
  appKeys:
  jwtSecret:
  apiTokenSalt:
  adminJwtSecret:

livenessProbe:
  initialDelaySeconds:
  periodSeconds:

readinessProbe:
  initialDelaySeconds:
  periodSeconds: