name: backoffice
namespace:
  name: 
replicaCount: 1

image:
  repository: 
  pullPolicy: IfNotPresent
  # Overrides the image tag whose default is the chart appVersion.
  tag: "0.0.0"

imagePullSecrets:
  - name: registry-secret

nameOverride: ""
fullnameOverride: ""

podAnnotations: {}
podSecurityContext: {}
securityContext: {}

service:
  type: ClusterIP
  port: 3003

resources: {}
autoscaling:
  enabled: false
  minReplicas: 2
  maxReplicas: 4
  targetCPUUtilizationPercentage: 80
  # targetMemoryUtilizationPercentage: 80

serviceAccount:
  create: false
  annotations: {}
  name: ""

nodeSelector: {}
tolerations: []

affinity: {}

docker_registry: 
  namespace: 
  docker_config_json:
    namespace:
    username: 
    password: 
    
env: 
  - name: VITE_API_URL
    value: https://cms.agency.hr-for-impact.fr
  - name: VITE_FRONT_URL
    value: https://www.agency.hr-for-impact.fr


livenessProbe:
  initialDelaySeconds:
  periodSeconds:

readinessProbe:
  initialDelaySeconds:
  periodSeconds:
