replicaCount: 2

image:
  repository: rg.fr-par.scw.cloud/thetribe/hr-for-impact
  pullPolicy: Always
  # Overrides the image tag whose default is the chart appVersion.
  tag: "0.0.2"

imagePullSecrets:
  - name: registry-secret

nameOverride: ""
fullnameOverride: ""

podAnnotations: {}
podSecurityContext: {}
securityContext: {}

service:
  type: ClusterIP
  port: 3000

resources: {}
autoscaling:
  enabled: false
  minReplicas: 2
  maxReplicas: 4
  targetCPUUtilizationPercentage: 80
  # targetMemoryUtilizationPercentage: 80

serviceAccount:
  create: false
  annotations: {}
  name: ""

nodeSelector: {}
tolerations: []
affinity: {}
docker_registry: 
  namespace: hr-for-impact
  docker_config_json:
    namespace: rg.fr-par.scw.cloud/thetribe
    username: thetribe
    password: cdfa1169-b000-4ec6-8af7-eb3ba581c4a4

certificate:
  enabled: false # set to true to use unique hostname certificates
  tld: "hr-for-impact.fr"  
  issuer:
    name: letsencrypt-prod
    type: dns
  hostnames:
    - hr-for-impact.fr

docker: 
  secretName: registry-secret

namespace:
  enabled: true
  name: hr-for-impact

name: web
env:
  - name: NEXT_IMAGE_ALLOWED_DOMAINS
    value:  picsum.photos,cdn.sarenza.com