name: web
namespace:
  name: 
replicaCount: 2

image:
  repository: 
  pullPolicy: IfNotPresent
  # Overrides the image tag whose default is the chart appVersion.
  tag: "0.0.0"

imagePullSecrets:
  - name: registry-secret

ingress:
  issuer: letsencrypt
  class: public
  domain: aerowork.fr
  subdomain: www

nameOverride: ""
fullnameOverride: ""

podAnnotations: {}
podSecurityContext: {}
securityContext: {}

service:
  type: ClusterIP
  port: 3000

resources: {}
autoscaling:
  enabled: false
  minReplicas: 2
  maxReplicas: 4
  targetCPUUtilizationPercentage: 80
  # targetMemoryUtilizationPercentage: 80

serviceAccount:
  create: false
  annotations: {}
  name: ""

nodeSelector: {}
tolerations: []

affinity: {}

docker_registry: 
  namespace: 
  docker_config_json:
    namespace:
    username: 
    password: 
env: []


livenessProbe:
  initialDelaySeconds:
  periodSeconds:

readinessProbe:
  initialDelaySeconds:
  periodSeconds: